credentials:
  usernames:
    alpisur:
      email: alpisur
      name: ALPISUR
      password: "$2b$12$9QKE1xKMCVP0HZCmk2w5JO3jFc0OuxoW1ewxe9//Y2PEFXFbv8H4G"
    utpl:
      email: utpl
      name: UTPL
      password: "$2b$12$0ndlHaiuXw3YQeeZkKYCAeByPsWcKb2igwhTegOZ9YmG7nQ3eZtp6"
cookie:
  expiry_days: 30
  key: "clave_secreta_aleatoria"
  name: "nombre_cookie_autenticacion"
preauthorized:
  emails:
    - aeulloa2@gmail.com
    - aeulloa3@gmail.com
